name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: '{{defaultContext}}'
        push: true
        tags: devvictorpersike/minha-pagina:latest, devvictorpersike/minha-pagina:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_RSA_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

    - name: Update docker-compose and deploy
      run: |
        ssh "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" "cd /opt/app-angular && \
        echo 'version: \"3\"
        services:
          angular-app:
            image: devvictorpersike/minha-pagina:${{ github.sha }}
            labels:
              - \"traefik.enable=true\"
              - \"traefik.docker.network=proxy\"
              - \"traefik.http.routers.angular.rule=Host(\`app.victorpersike.dev.br\`)\"
              - \"traefik.http.routers.angular.entrypoints=https\"
              - \"traefik.http.routers.angular.tls=true\"
              - \"traefik.http.services.angular.loadbalancer.server.port=80\"
            networks:
              - proxy
            restart: always

        networks:
          proxy:
            external: true' > docker-compose.yml && \
        docker-compose pull && \
        docker-compose up -d --scale angular-app=2 --no-recreate && \
        sleep 10 && \
        docker-compose up -d --force-recreate"
