name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: '{{defaultContext}}'
        push: true
        tags: devvictorpersike/minha-pagina:latest, devvictorpersike/minha-pagina:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_RSA_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

    - name: Deploy using Docker Service
      run: |
        ssh "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" "cd /opt/app-angular && \
        docker service update --image devvictorpersike/minha-pagina:${{ github.sha }} \
        --update-parallelism 1 \
        --update-delay 10s \
        --update-order start-first \
        --with-registry-auth \
        agular-app_angular-app || \
        docker stack deploy -c docker-compose.yml agular-app --with-registry-auth"
